# Copyright Vespa.ai. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

# See https://cloud.vespa.ai/automated-deployments for details
# The ${VESPA_TEAM_VESPACLOUD_CORD_19_API_KEY} is a secret in this repository —
# this is used to deploy applications to Vespa Cloud

name: Deploy cord-19-search to Vespa Cloud
on:
  push:
    branches: [ main ]

env:
  API_KEY: ${{ secrets.VESPA_TEAM_VESPACLOUD_CORD_19_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    # Check out the source code from the repository
    - uses: actions/checkout@v3

    # Vespa uses Java 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    # Find Vespa version of current production deployment
    - name: Find compile version
      working-directory: .
      run: mvn -B clean vespa:compileVersion -DapiKey="${API_KEY}"
    
    # Build the application package and the tester bundle
    - name: Build with Maven
      working-directory: .
      run: mvn -B package -Dvespa.compile.version="$(cat target/vespa.compile.version)"
    
    # Deploy to Vespa Cloud
    - name: Deploy with Maven
      working-directory: .
      run: |
        mvn -B vespa:submit \
           -Drepository="$(git config --get remote.origin.url)" \
           -Dbranch="$(git rev-parse --abbrev-ref HEAD)" \
           -Dcommit="$(git rev-parse HEAD)" \
           -DauthorEmail="$(git log -1 --format=%aE)" \
           -DsourceUrl="$(git config --get remote.origin.url | sed 's+git@\(.*\):\(.*\)\.git+https://\1/\2+')/commit/$(git rev-parse HEAD)" \
           -DapiKey="${API_KEY}"
